rule all: 
    input:
        expand("{prefix}/{reads}/reads_on_contigs.bam", prefix = config["output_directory"], reads = config["reads_name"])

rule reads_on_contigs_mapping :
    params: 
        reads_type = config["sequencing_technology"]
    input:
        script = "workflow/scripts/mapping.sh",
        reads_path = config["reads_path"],
        contigs = config["assembly"]
    output: "{prefix}/{reads_name}/reads_on_contigs.bam"
    shell: "./{input.script} {output} {input.contigs} {params.reads_type} {input.reads_path} "
