---
# No "_" in the names

##### Reads #####
pacbio-hifi:
 - name: salad-irg-pacbio-hifi
   path: ../data/SMRTcell1-M8-fev-sal-irg-1.hifi_reads.fastq

pacbio-clr:
 - name: .
   path: .

ont:
 - name: .
   path: .

illumina:
 - name: salad-run1-illumina
   forward: ../data/cleaned_run1_R1.fastq 
   reverse: ../data/cleaned_run1_R2.fastq



##### Assemblers #####
pacbio-hifi-assemblers:
 - metaMDBG
 - metaflye
 - hifiasm-meta

pacbio-clr-assemblers:
# - metaflye
# - miniasm

ont-assemblers:
# - metaflye
# - miniasm

pacbio-hifi-illumina-hybrid-assemblers:
# - operaMS

pacbio-clr-illumina-hybrid-assemblers:
# - operaMS

ont-illumina-hybrid-assemblers:
# - operaMS

##### Evaluation #####
reference-genomes: .
abundance-information: .

sample-comparison-type : illumina
sample-comparison-reads : ../data/cleaned_run1_combined.fastq

metrics:
# - reference-based
# - reference-free-sample-comparison
 - reference-free
# - bin-quality-based
# -reference-based-binning-evaluation


