---
# No "_" in the names

##### Reads #####
pacbio-hifi : 
 - name : test-hifi
   path : ../Hi-Fi/data/input_reads/SMRTcell1-M1-juil-conc-irg-A2-1.hifi-reads.fastq

pacbio-clr : 
 - name : test-lofi
   path : ../Hi-Fi/data/input_reads/SRR8073713.fastq


##### Assemblers #####
pacbio-hifi-assemblers :
#  - metaMDBG
#  - metaflye
  - hifiasm-meta

pacbio-clr-assemblers :
#  - metaflye

##### Evaluation #####
reference-genomes : ../Hi-Fi/data/input_reference_genomes/

abundance-information : ../abundance_info.csv

metrics : 
# -reference-based


