---
# No "_" in the names

##### Reads #####
long-reads-hi-fi : 
 - name : test_hifi
   path : ../Hi-Fi/data/input_reads/SMRTcell1-M1-juil-conc-irg-A2-1.hifi-reads.fastq

##### Assemblers #####
long-reads-hi-fi-assemblers :
#  - metaMDBG
  - metaflye

##### Evaluation #####
reference-genomes : ../data/test...
abundance-information : ../data/test...

metrics : 
 -reference-based


