##### Inputs #####
### Samples ###
# long reads used for assembly and evaluation
samples :
# - name : zymo
#   read_path : /groups/genscale/nimauric/long_reads/zymoD6331.fastq
# - name : salad-irg 
#   read_path : /groups/genscale/nimauric/long_reads/SMRTcell1-M8-fev-sal-irg-1.hifi_reads.fastq 
# - name : human-gut
#   read_path : /groups/genscale/nimauric/long_reads/biocolective_139369_vegan_gut.fastq
 - name : Pseudomonas_fluorescens_1X
   read_path : ../CWL_subsample/Pseudomonas_fluorescens_1X.fastq
# - name : Pseudomonas_fluorescens_3X
#   read_path : ../CWL_subsample/Pseudomonas_fluorescens_3X.fastq
# - name : Pseudomonas_fluorescens_5X
#   read_path : ../CWL_subsample/Pseudomonas_fluorescens_5X.fastq
# - name : Pseudomonas_fluorescens_10X
#   read_path : ../CWL_subsample/Pseudomonas_fluorescens_10X.fastq

# - name : salad_irg+Pseudomonas_fluorescens_1X
#   read_path : ../CWL_subsample/salad_irg+Pseudomonas_fluorescens_1X.fastq
# - name : salad_irg+Pseudomonas_fluorescens_3X
#   read_path : ../CWL_subsample/salad_irg+Pseudomonas_fluorescens_3X.fastq
# - name : salad_irg+Pseudomonas_fluorescens_5X
#   read_path : ../CWL_subsample/salad_irg+Pseudomonas_fluorescens_5X.fastq
# - name : salad_irg+Pseudomonas_fluorescens_10X
#   read_path : ../CWL_subsample/salad_irg+Pseudomonas_fluorescens_10X.fastq

# - name : Pseudomonas_fluorescens_1X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/Pseudomonas_fluorescens_1X_simulated.fastq
# - name : Pseudomonas_fluorescens_3X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/Pseudomonas_fluorescens_3X_simulated.fastq
# - name : Pseudomonas_fluorescens_5X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/Pseudomonas_fluorescens_5X_simulated.fastq
# - name : Pseudomonas_fluorescens_10X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/Pseudomonas_fluorescens_10X_simulated.fastq
# - name : salad_irg+Pseudomonas_fluorescens_1X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/salad_irg+Pseudomonas_fluorescens_1X_simulated.fastq
# - name : salad_irg+Pseudomonas_fluorescens_3X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/salad_irg+Pseudomonas_fluorescens_3X_simulated.fastq
# - name : salad_irg+Pseudomonas_fluorescens_5X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/salad_irg+Pseudomonas_fluorescens_5X_simulated.fastq
# - name : salad_irg+Pseudomonas_fluorescens_10X_simulated
#   read_path : /scratch/nimauric/CWL_subsample/simulate_reads/salad_irg+Pseudomonas_fluorescens_10X_simulated.fastq

# - name : salad_irg+Pseudomonas_fluorescens_10X
#   read_path : ../CWL_subsample/salad_irg+Pseudomonas_fluorescens_10X.fastq



# (optional), short reads, may be used for binning or evaluation. Should be from the same sample as the long reads
short_reads_1 : /groups/genscale/nimauric/short_reads/merged_run_R1.fastq
short_reads_2 : /groups/genscale/nimauric/short_reads/merged_run_R2.fastq
# (optional), short read assembly, may be used for assembly. Should be from the same sample as the long reads
short_read_assembly : /groups/genscale/nimauric/short_reads/short_read_assembly.fa


# (optional), long reads used for cobinning. Should be from a similar sample as the studied sample
additional_reads : 
 - name : conc-irg
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M1-juil-conc-irg-A2-1.hifi-reads.fastq
 - name : conc-rhizo
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M2-juil-conc-rhizo-A2-1.hifi-reads.fastq
 - name : aub-irg-A22
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M3-oct-aub-irg-A22-1.hifi-reads.fastq
 - name : aub-rhizo-A24
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M4-oct-aub-rhizo-A24-4.hifi_reads.fastq
 - name : aub-rhizo-C20
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M5-oct-aub-rhizo-C20-8.hifi_reads.fastq
 - name : aub-irg-D6
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M6-oct-aub-irg-D6-2.hifi_reads.fastq
 - name : poiv-irg-B1
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M7-oct-poiv-irg-B1-2.hifi_reads.fastq
 - name : sal-rhizo
   path : /groups/genscale/nimauric/long_reads/SMRTcell1-M9-fev-sal-rhizo-A10-1.hifi_reads.fastq

# (optional), used for evaluation
reference_genomes :
### Soil from blast ###
# - /groups/genscale/nimauric/soil_references/flavobacterium_sp_KS_LB2.fasta
# - /groups/genscale/nimauric/soil_references/Gemmatirosa_kalamazoonesis.fasta
# - /groups/genscale/nimauric/soil_references/Humisphaera_borealis.fasta
# - /groups/genscale/nimauric/soil_references/Thauera_sp_MZ1T.fasta
# - /groups/genscale/nimauric/soil_references/Mesorhizobium_sp.fasta
### Soil from 5 x 3 bins ###
# - /groups/genscale/nimauric/soil_references/Lysobacter_terrestris.fasta
# - /groups/genscale/nimauric/soil_references/Bradyrhizobium_arachidis.fasta
# - /groups/genscale/nimauric/soil_references/Streptomyces_sp_135.fasta
# - /groups/genscale/nimauric/soil_references/Bradyrhizobium_erythrophlei.fasta
# - /groups/genscale/nimauric/soil_references/Streptomyces_sp_MBT27.fasta
# - /groups/genscale/nimauric/soil_references/Bradyrhizobium_sp_4.fasta
# - /groups/genscale/nimauric/soil_references/Bradyrhizobium_sp_A19.fasta 
# - /groups/genscale/nimauric/soil_references/Streptomyces_sp_MST_110588.fasta
# - /groups/genscale/nimauric/soil_references/Burkholderia_ubonensis.fasta
# - /groups/genscale/nimauric/soil_references/Streptomyces_venezuelae.fasta
# - /groups/genscale/nimauric/soil_references/Cupriavidus_pauculus.fasta
# - /groups/genscale/nimauric/soil_references/Nitrospira_tepida.fasta
# - /groups/genscale/nimauric/soil_references/Enhydrobacter_sp.fasta
# - /groups/genscale/nimauric/soil_references/Pseudomonas_sp_ABC1.fasta
# - /groups/genscale/nimauric/soil_references/Streptomyces_liliifuscus.fasta
### Soil spiked 
# - /groups/genscale/nimauric/soil_references/Pseudomonas_fluorescens.fasta
- /groups/genscale/nimauric/soil_references/Pseudomonas_fluorescens_IMGN2.fasta
### Zymo ###
# - /groups/genscale/nimauric/ZymoD6331/Zymo_merged.fasta 
# - /groups/genscale/nimauric/ZymoD6331/Akkermansia_muciniphila.fasta
# - /groups/genscale/nimauric/ZymoD6331/Candida_albican.fasta
# - /groups/genscale/nimauric/ZymoD6331/Enterococcus_faecalis.fasta
# - /groups/genscale/nimauric/ZymoD6331/Escherichia_coli_B3008.fasta
# - /groups/genscale/nimauric/ZymoD6331/Faecalibacterium_prausnitzii.fasta
# - /groups/genscale/nimauric/ZymoD6331/Methanobrevibacter_smithii.fasta
# - /groups/genscale/nimauric/ZymoD6331/Saccharomyces_cerevisiae.fasta
# - /groups/genscale/nimauric/ZymoD6331/Bacteroides_fragilis.fasta
# - /groups/genscale/nimauric/ZymoD6331/Clostridioides_difficile.fasta
# - /groups/genscale/nimauric/ZymoD6331/Escherichia_coli_B1109.fasta
# - /groups/genscale/nimauric/ZymoD6331/Escherichia_coli_B766.fasta
# - /groups/genscale/nimauric/ZymoD6331/Fusobacterium_nucleatum.fasta
# - /groups/genscale/nimauric/ZymoD6331/Prevotella_corporis.fasta
# - /groups/genscale/nimauric/ZymoD6331/Salmonella_enterica.fasta
# - /groups/genscale/nimauric/ZymoD6331/Bifidobacterium_adolescentis.fasta
# - /groups/genscale/nimauric/ZymoD6331/Clostridium_perfringens.fasta
# - /groups/genscale/nimauric/ZymoD6331/Escherichia_coli_b2207.fasta
# - /groups/genscale/nimauric/ZymoD6331/Escherichia_coli_JM109.fasta
# - /groups/genscale/nimauric/ZymoD6331/Lactobacillus_fermentum.fasta
# - /groups/genscale/nimauric/ZymoD6331/Roseburia_hominis.fasta
# - /groups/genscale/nimauric/ZymoD6331/Veillonella_rogosae.fasta

# (optional), used for evaluation
abundance_information : /groups/genscale/nimauric/long_reads/soil_abundance.csv # /groups/genscale/nimauric/long_reads/zymo_abundance.csv #


### External programs ###
# (optional), used for evaluation via taxonomic assignation
kraken2bin : /scratch/nimauric/kraken2/bins/
kraken2db : /groups/genscale/nimauric/databases/standard_kraken_database/
kronabin : /scratch/nimauric/KronaTools-2.7/bin/


# (optional), 
operaMS_path : ../programs/OPERA-MS

##### Controls #####
### Assembly and binning ###
assemblers : # uncomment assemblers to use them
 - metaMDBG
# - operaMS # requires short_read_assembly and operaMS_path
# - metaflye
# - hifiasm_meta

short_read_binning : false # requires short_reads_1 and short_reads_2
short_read_cobinning : false # requires short_reads_1 and short_reads_2
additional_reads_cobinning : false # requires at least one additional_reads 

binning : false
binners : 
  - metabat2

### Evaluation ###
# contig analysis
metaquast : true # requires reference_genomes
read_mapping_evaluation : false 
short_read_mapping_evaluation : false # requires short_reads_1 and short_reads_2
reference_mapping_evaluation : false # requires reference_genomes

# bins analysis
checkm : false
kraken2_on_bins : false #/!\ Require having done binning separatly on a previous step, requires kraken2bin; kraken2db and kronabin
target_bins : #/!\ Require having done binning separatly on a previous step, requires kraken2bin; kraken2db and kronabin
# HQ
 - 272
 - 306
 - 390
 - 255
 - 112
# MQ
 - 253
 - 343
 - 226
 - 170
 - 242
# LQ
 - 123
 - 194
 - 154
 - 177
 - 256

# Fractionned read analysis
fractions : 
  - full
#  - mapped 
#  - unmapped
fastqc : false 
kraken2 : false # requires kraken2bin; kraken2db and kronabin
kat : false

##### Parameters #####
### Functional parameters ###
read_mapping_threshold : 0 #minimum total alignement length for a read to be considered mapped to a contig
metaquast_min_identity : 95

### Ressources parameters ###

# Mapping
rules_mapping :
  threads: 24
  memory: 100G 
  time: 1*24*60 #in minutes

# Assembly 
rule_metaMDBG_assembly: 
  threads: 48
  memory: 35G 
  time: 2*24*60 #in minutes

rule_metaflye_assembly: 
  threads: 48
  memory: 60G 
  time: 1*24*60 #in minutes

rule_hifiasm_meta_assembly: 
  threads: 48
  memory: 80G 
  time: 2*24*60 #in minutes

rule_operaMS_assembly : 
  threads: 48
  memory: 200G 
  time: 5*24*60 #in minutes

# Binning
rules_metabat2_binnings : 
  threads: 16
  memory: 20G 
  time: 12*60 #in minutes

# Contig quality analysis
rule_metaquast: 
  threads: 1
  memory: 20G 
  time: 24*60 #in minutes

# Bin quality analysis
rule_checkm: 
  threads: 16
  memory: 100G 
  time: 24*60 #in minutes

rule_checkm_report_writer : 
  threads: 1
  memory: 100G 
  time: 1*60 #in minutes

rule_kraken2_on_bins : 
  threads: 12
  memory: 100G 
  time: 4*60 #in minutes

# read quality analysis 
rule_extract_unmapped_reads : 
  threads: 24
  memory: 100G 
  time: 24*60 #in minutes

rule_kraken2 : 
  threads: 12
  memory: 100G 
  time: 4*60 #in minutes

rule_kat_sect : 
  threads: 12
  memory: 200G 
  time: 4*60 #in minutes
