---
# No "_" in the names

##### Reads #####
pacbio-hifi: 
 - name: test-hifi
   path: ../Hi-Fi/data/input_reads/SMRTcell1-M1-juil-conc-irg-A2-1.hifi-reads.fastq

pacbio-clr: 
 - name: test-pacbio-clr 
   path: ../Hi-Fi/data/input_reads/SRR8073714.fastq

ont: 
 - name: test-ont
   path: ../Hi-Fi/data/input_reads/SRR8073713.fastq

illumina: 
 - name: test-illumina
   forward: ../Hi-Fi/data/input_reads/SRR8073716-1.fastq
   reverse: ../Hi-Fi/data/input_reads/SRR8073716-2.fastq


##### Assemblers #####
pacbio-hifi-assemblers:
# - metaMDBG
# - metaflye
# - hifiasm-meta

pacbio-clr-assemblers:
 - metaflye
# - miniasm

ont-assemblers:
# - metaflye
# - miniasm

pacbio-clr-illumina-hybrid-assemblers:
# - operaMS

ont-illumina-hybrid-assemblers:
# - operaMS

##### Evaluation #####
reference-genomes: ../Hi-Fi/data/input_reference_genomes/

abundance-information: ../abundance_info.csv

metrics: 
 - reference-based
 - reference-free
 - bin-counting
# -reference-based-binning-evaluation



