---
long_reads :
 - toySRR8073713
# - SRR8073714
# - SRR8073713

short_reads : 
 - SRR8073716

long_reads_assemblers :
# - metaflye
# - canu
# - miniasm
# - flye_polish_canu
# - flye_polish_miniasm

hybrid_assemblers : 
 - operams
