---
long_reads :
# - Bmock-PacBio
# - Bmock-ONT-full

short_reads : 
# - Bmock-Illumina

hifi_reads : 
 - SRR13128014 
# - concombre_rhizo.fastq
# - concombre_irg.fastq

long_reads_assemblers :
# - metaflye
# - canu
# - miniasm
# - flye_polish_canu
# - flye_polish_miniasm

hybrid_assemblers : 
# - operams

hifi_assemblers :
  - metaflye
#  - hifiasm
  - metamdbg

metrics : 
 - references-based
 - references-free
 - binning-based
# - none
