analysis_name: genome_informatics_equal_bases

##### Inputs #####

### Samples ###
# long reads used for assembly and evaluation
samples: 
 - name: zymo
   read_path: /groups/genscale/nimauric/long_reads/zymoD6331.fastq
 - name: salad-irg-equal-bases 
   read_path: /groups/genscale/nimauric/long_reads/genome_informatics/soil_equal_bases.fastq 
 - name: human-gut-equal-bases
   read_path: /groups/genscale/nimauric/long_reads/genome_informatics/vegan_gut_equal_bases.fastq

# (optional), short reads, may be used for binning or evaluation. Should be from the same sample as the long reads
short_reads_1: /groups/genscale/nimauric/short_reads/merged_run_R1.fastq
short_reads_2: /groups/genscale/nimauric/short_reads/merged_run_R2.fastq
# (optional), short read assembly, may be used for assembly. Should be from the same sample as the long reads
short_read_assembly: /groups/genscale/nimauric/short_reads/short_read_assembly.fa

# (optional), long reads used for cobinning. Should be from a similar sample as the studied sample
additional_reads: 
 - name: none
   path: none


# (optional), used for evaluation
reference_genomes: 
 - none

# (optional), used for evaluation
abundance_information: none # /groups/genscale/nimauric/long_reads/zymo_abundance.csv #

# (optional), to evaluate bins and assemblies generated by external programs
custom_assembly_path: none
custom_bins_path: none #/groups/genscale/nimauric/carole_data/5-dereplicated-bins/metaMDBG_assembly_salad_irg_2024_03_06/ # bins should be in .fa format, with one of them named "bin.1.fa"

### External programs ###
# (optional), used for evaluation via taxonomic assignation
kraken2bin: /scratch/nimauric/kraken2/bins/
kraken2db: /groups/genscale/nimauric/databases/standard_kraken_database/
kronabin: /scratch/nimauric/KronaTools-2.7/bin/

gtdbtk_database: /groups/genscale/nimauric/databases/gtdbtk_release220/
mash_database: outputs/mash_db #if doesn't exist, will be created here

# (optional), 
operaMS_path: ../programs/OPERA-MS

##### Controls #####
### Assembly and binning ###

assemblers: # uncomment assemblers to use them
 - metaMDBG
# - custom_assembly # requires custom_assembly_path
# - operaMS # requires short_read_assembly and operaMS_path
 - metaflye
 - hifiasm_meta

short_read_binning: false # requires short_reads_1 and short_reads_2
short_read_cobinning: false # requires short_reads_1 and short_reads_2
additional_reads_cobinning: false # requires at least one additional_reads 

binning: true
binners: 
  - metabat2
#  - custom # requires custom_bins_path

### Evaluation ###
# contig analysis
metaquast: false # requires reference_genomes
read_mapping_evaluation: true 
short_read_mapping_evaluation: false # requires short_reads_1 and short_reads_2
reference_mapping_evaluation: false # requires reference_genomes

# bins analysis
checkm: true
gtdbtk: false # requires gtdbtk_database and mash_database
kraken2_on_bins: false #/!\ Require having done binning separatly on a previous step, requires kraken2bin; kraken2db and kronabin
target_bins: #/!\ Require having done binning separatly on a previous step, requires kraken2bin; kraken2db and kronabin
 - 1

# Fractionned read analysis
fractions: 
  - full
#  - mapped 
  - unmapped
fastqc: false 
kraken2: false # requires kraken2bin; kraken2db and kronabin
kat: true

##### Parameters #####
### Functional parameters ###
read_mapping_threshold: 0 #minimum total alignement length for a read to be considered mapped to a contig
metaquast_min_identity: 95

### Ressources parameters ###

# Mapping
rules_mapping: 
  threads: 24
  memory: 100G 
  time: 1*24*60 #in minutes

# Assembly 
rule_metaMDBG_assembly: 
  threads: 48
  memory: 35G 
  time: 2*24*60 #in minutes

rule_metaflye_assembly: 
  threads: 48
  memory: 60G 
  time: 1*24*60 #in minutes

rule_hifiasm_meta_assembly: 
  threads: 48
  memory: 80G 
  time: 2*24*60 #in minutes

rule_operaMS_assembly: 
  threads: 48
  memory: 200G 
  time: 5*24*60 #in minutes

# Binning
rules_metabat2_binnings: 
  threads: 16
  memory: 20G 
  time: 12*60 #in minutes

# Contig quality analysis
rule_metaquast: 
  threads: 1
  memory: 20G 
  time: 24*60 #in minutes

rule_read_contig_mapping_evaluation :
  threads: 1
  memory: 10G 
  time: 2*60 #in minutes


# Bin quality analysis
rule_checkm: 
  threads: 16
  memory: 100G 
  time: 24*60 #in minutes

rule_checkm_report_writer: 
  threads: 1
  memory: 100G 
  time: 1*60 #in minutes

rule_kraken2_on_bins: 
  threads: 12
  memory: 100G 
  time: 4*60 #in minutes

rule_gtdbtk_on_bins: 
  threads: 20
  memory: 100G 
  time: 8*60 #in minutes

rule_read_contig_mapping_plot:
  threads: 1
  memory: 30G 
  time: 2*60 #in minutes

  
# read quality analysis 
rule_extract_unmapped_reads: 
  threads: 24
  memory: 100G 
  time: 24*60 #in minutes

rule_kraken2: 
  threads: 12
  memory: 100G 
  time: 4*60 #in minutes

rule_kat_sect: 
  threads: 12
  memory: 200G 
  time: 4*60 #in minutes
