---
long_reads :
# - toy-SRR8073713
 - SRR8073714
# - SRR8073713
 - subsampled-SRR8073713

long_reads_assemblers :
 - metaflye
 - miniasm
# - flye_polish_miniasm
# - canu
# - flye_polish_canu

hifi_reads : 
 - SRR15275210

hifi_assemblers :
  - metaflye
  - hifiasm

metrics : 
 - references-based
 - references-free
