
### Input ###
assembly: "/path/to/assembly.fasta" # Required

sequencing_technology: PacBio-HiFi # Required: Illumina, PacBio-HiFi (does not need to be the reads used for the assembly)
reads_name: name # Required
reads_path: 
 - /path/to/reads1.fastq
 - /path/to/reads2.fastq # Optional, for paired-end reads

bins: "/path/to/bins.fasta" # Optional. If not included: Only evaluate contigs
binning_name: "binning_name" # Required if bins are included. 

reference_genomes: # Optional
 - name: name
   path: path/to/reference_genome.fasta

### Output ###
output_directory: "path/to/output_directory" 

### Controls ###
# mapped/unmapped reads analysis
fastQC: false #read quality 
reads_kraken2: false #taxonomic assignation 
kat: false #k-mer composition 
 
# contigs analysis
reads_on_contigs_mapping: false 
contigs_kraken2: false
metaquast: false # Require reference genomes

# bins analysis
bins_analysis: false # If true, uses checkm, sort bins in categories, 
  # and then aggregates the results of fastQC, kat and reads_on_contigs_mapping by bin category
  # and aggregates the results of kraken2, fastQC, kat and reads_on_contigs_mapping by bin ? 

### Ressources parameters ###
# for each analysis that uses significant ressources (How much is significant ?): 
rule_1: 
  threads: 1
  memory: 1G
  time: 1:00:00

### Tools parameters ###
# How much control should I give to the user for each analysis ?
# Kraken2
kraken2bin: /scratch/nimauric/kraken2/bins/
kraken2db: /groups/genscale/nimauric/databases/standard_kraken_database/
kronabin: /scratch/nimauric/KronaTools-2.7/bin/




