---
long_reads :
 - SRR8073714
# - SRR8073713
# - toy-SRR8073713
# - subsampled-SRR8073713
# - SRR15275210

short_reads : 
 - SRR8073716

long_reads_assemblers :
 - metaflye
# - canu
# - miniasm
# - flye_polish_canu
# - flye_polish_miniasm

hybrid_assemblers : 
 - operams
