### Input ###
assembly: /scratch/nimauric/mapler/outputs/zymo/metaMDBG/assembly.fasta

reads: 
 - name: Zymo_HiFi
   path: /groups/genscale/nimauric/long_reads/zymoD6331.fastq
   type: PacBio-HiFi 


### Output ###
output_directory: outputs/metaMDBG_Zymo
analysis_name: mapping_test